export const host = 'https://developer.mozilla.org';

const attr = [
  [
    '/en-US/docs/Web/HTML/Attributes/accept',
    'accept(en-US)'
  ],
  [
    '/zh-CN/docs/Web/HTML/Attributes/autocomplete',
    'autocomplete'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/capture',
    'capture(en-US)'
  ],
  [
    '/zh-CN/docs/Web/HTML/Attributes/crossorigin',
    'crossorigin'
  ],
  [
    '/zh-CN/docs/Web/HTML/Attributes/disabled',
    'disabled'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/elementtiming',
    'elementtiming(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/for',
    'for(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/max',
    'max(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/maxlength',
    'maxlength(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/min',
    'min(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/minlength',
    'minlength(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/multiple',
    'multiple(en-US)'
  ],
  [
    '/zh-CN/docs/Web/HTML/Attributes/pattern',
    'pattern'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/readonly',
    'readonly(en-US)'
  ],
  [
    '/zh-CN/docs/Web/HTML/Attributes/rel',
    'rel'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/required',
    'required(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/size',
    'size(en-US)'
  ],
  [
    '/en-US/docs/Web/HTML/Attributes/step',
    'step(en-US)'
  ]
];

const global_attr = [
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/accesskey',
    'accesskey'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/autocapitalize',
    'autocapitalize'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/autofocus',
    'autofocus'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/class',
    'class'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/contenteditable',
    'contenteditable'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/contextmenu',
    'contextmenu'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/data-*',
    'data-*'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/dir',
    'dir'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/draggable',
    'draggable'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/enterkeyhint',
    'enterkeyhint'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/exportparts',
    'exportparts'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/hidden',
    'hidden'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/id',
    'id'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/inert',
    'inert'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/inputmode',
    'inputmode'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/is',
    'is'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/itemid',
    'itemid'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/itemprop',
    'itemprop'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/itemref',
    'itemref'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/itemscope',
    'itemscope'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/itemtype',
    'itemtype'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/lang',
    'lang'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/nonce',
    'nonce'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/part',
    'part'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/popover',
    'popover'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/slot',
    'slot'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/spellcheck',
    'spellcheck'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/style',
    'style'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/tabindex',
    'tabindex'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/title',
    'title'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/translate',
    'translate'
  ],
  [
    '/zh-CN/docs/Web/HTML/Global_attributes/virtualkeyboardpolicy',
    'virtualkeyboardpolicy'
  ]
];

const elements = [
  [
    '/zh-CN/docs/Web/HTML/Element/a',
    'a'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/abbr',
    'abbr'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/acronym',
    'acronym'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/address',
    'address'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/applet',
    'applet'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/area',
    'area'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/article',
    'article'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/aside',
    'aside'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/audio',
    'audio'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/b',
    'b'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/base',
    'base'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/bdi',
    'bdi'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/bdo',
    'bdo'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/bgsound',
    'bgsound'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/big',
    'big'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/blink',
    'blink'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/blockquote',
    'blockquote'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/body',
    'body'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/br',
    'br'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/button',
    'button'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/canvas',
    'canvas'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/caption',
    'caption'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/center',
    'center'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/cite',
    'cite'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/code',
    'code'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/col',
    'col'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/colgroup',
    'colgroup'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/data',
    'data'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/datalist',
    'datalist'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/dd',
    'dd'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/del',
    'del'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/details',
    'details'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/dfn',
    'dfn'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/dialog',
    'dialog'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/dir',
    'dir'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/div',
    'div'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/dl',
    'dl'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/dt',
    'dt'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/em',
    'em'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/embed',
    'embed'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/fieldset',
    'fieldset'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/figcaption',
    'figcaption'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/figure',
    'figure'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/font',
    'font'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/footer',
    'footer'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/form',
    'form'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/frame',
    'frame'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/frameset',
    'frameset'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/Heading_Elements',
    'h1'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/head',
    'head'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/header',
    'header'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/hgroup',
    'hgroup'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/hr',
    'hr'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/html',
    'html'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/i',
    'i'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/iframe',
    'iframe'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/image',
    'image'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/img',
    'img'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/input',
    'input'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/ins',
    'ins'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/kbd',
    'kbd'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/keygen',
    'keygen'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/label',
    'label'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/legend',
    'legend'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/li',
    'li'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/link',
    'link'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/main',
    'main'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/map',
    'map'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/mark',
    'mark'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/marquee',
    'marquee'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/menu',
    'menu'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/menuitem',
    'menuitem'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/meta',
    'meta'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/meter',
    'meter'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/nav',
    'nav'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/nobr',
    'nobr'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/noembed',
    'noembed'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/noframes',
    'noframes'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/noscript',
    'noscript'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/object',
    'object'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/ol',
    'ol'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/optgroup',
    'optgroup'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/option',
    'option'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/output',
    'output'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/p',
    'p'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/param',
    'param'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/picture',
    'picture'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/plaintext',
    'plaintext'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/portal',
    'portal'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/pre',
    'pre'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/progress',
    'progress'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/q',
    'q'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/rb',
    'rb'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/rp',
    'rp'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/rt',
    'rt'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/rtc',
    'rtc'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/ruby',
    'ruby'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/s',
    's'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/samp',
    'samp'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/script',
    'script'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/section',
    'section'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/select',
    'select'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/slot',
    'slot'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/small',
    'small'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/source',
    'source'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/spacer',
    'spacer'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/span',
    'span'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/strike',
    'strike'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/strong',
    'strong'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/style',
    'style'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/sub',
    'sub'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/summary',
    'summary'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/sup',
    'sup'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/table',
    'table'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/tbody',
    'tbody'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/td',
    'td'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/template',
    'template'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/textarea',
    'textarea'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/tfoot',
    'tfoot'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/th',
    'th'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/thead',
    'thead'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/time',
    'time'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/title',
    'title'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/tr',
    'tr'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/track',
    'track'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/tt',
    'tt'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/u',
    'u'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/ul',
    'ul'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/var',
    'var'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/video',
    'video'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/wbr',
    'wbr'
  ],
  [
    '/zh-CN/docs/Web/HTML/Element/xmp',
    'xmp'
  ]
];

export const db =[...elements, ...attr, ...global_attr]